{
 "title": "Media Dashboard",
 "tags": [
  "sonarr",
  "readarr",
  "radarr",
  "lidarr",
  "prowlarr",
  "sabnzbd",
  "music",
  "movies",
  "tv",
  "media"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "sabnzbd_instance",
    "label": "SABnzbd Instance",
    "query": {
     "query": "label_values({__name__=~\"sabnzbd_.*\"},instance)"
    }
   },
   {
    "name": "radarr_instance",
    "label": "Radarr Instance",
    "query": {
     "query": "label_values({__name__=~\"radarr_.*\"},instance)"
    }
   },
   {
    "name": "sonarr_instance",
    "label": "Sonarr Instance",
    "query": {
     "query": "label_values({__name__=~\"sonarr_.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All Queues",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(radarr_queue_total[5m])",
     "legendFormat": "Radarr"
    },
    {
     "expr": "sum(avg_over_time(sonarr_queue_total[5m]))",
     "legendFormat": "sonarr"
    },
    {
     "expr": "avg_over_time(sabnzbd_queue_length[5m])",
     "legendFormat": "sabnzbd"
    }
   ]
  },
  { "title": "SABnzbd - ${sabnzbd_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "sabnzbd_instance" },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sabnzbd_downloaded_bytes{instance=~\"${sabnzbd_instance}\"})",
     "legendFormat": "Lifetime"
    },
    {
     "expr": "max(increase(sabnzbd_downloaded_bytes{instance=~\"${sabnzbd_instance}\"}[$__range]))",
     "legendFormat": "Recent"
    },
    {
     "expr": "sabnzbd_queue_length{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "sabnzbd_total_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Queue Size"
    },
    {
     "expr": "sabnzbd_remaining_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Remaining"
    },
    {
     "expr": "sum(sabnzbd_server_articles_success{instance=~\"${sabnzbd_instance}\"}) / sum(sabnzbd_server_articles_total{instance=~\"${sabnzbd_instance}\"})",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_quota_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "1 - max(sabnzbd_remaining_quota_bytes{instance=~\"${sabnzbd_instance}\"} / sabnzbd_quota_bytes{instance=~\"${sabnzbd_instance}\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sabnzbd_remaining_quota_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_article_cache_articles{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Articles"
    },
    {
     "expr": "sabnzbd_article_cache_bytes{instance=~\"${sabnzbd_instance}\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"sabnzbd-exporter\"}",
     "legendFormat": "Status"
    }
   ]
  },
  { "title": "Radarr - ${radarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "radarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_system_status{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"radarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_downloaded_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "radarr_movie_monitored_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "radarr_movie_wanted_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_queue_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "radarr_movie_downloaded_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "radarr_history_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "History"
    },
    {
     "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "radarr_rootfolder_freespace_bytes{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_quality_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"radarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"radarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "radarr_system_health_issues{instance=~\"${radarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sonarr - ${sonarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "sonarr_instance",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_system_status{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - container_start_time_seconds{container=\"sonarr\"}",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_queue_total{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "Queued"
      },
      {
       "expr": "sonarr_history_total{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "History"
      },
      {
       "expr": "sonarr_episode_downloaded_total{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "Downloaded"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(sonarr_series_monitored_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Series Monitored"
      },
      {
       "expr": "max(sonarr_series_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Series Total"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(sonarr_season_monitored_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Seasons Monitored"
      },
      {
       "expr": "max(sonarr_season_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Seasons Total"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(sonarr_episode_missing_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Episodes Missing"
      },
      {
       "expr": "max(sonarr_episode_total{instance=~\"${sonarr_instance}\"})",
       "legendFormat": "Episodes Total"
      }
     ]
    },
    {
     "title": "Qualities",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_episode_quality_total{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "{{quality}}"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval]))",
       "legendFormat": "Network Transmit"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval])) * -1",
       "legendFormat": "Network Receive"
      }
     ]
    },
    {
     "title": "Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sonarr_series_filesize_bytes{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "System Health Issues",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
     "targets": [
      {
       "expr": "sonarr_system_health_issues{instance=~\"${sonarr_instance}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}