apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: home
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbhydra2
      version: 10.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nzbhydra2
  values:
    image:
      # -- image repository
      repository: linuxserver/nzbhydra2
      # -- image tag
      tag: v7.3.0-ls17
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: America/Los_Angeles
      # HOST_WHITELIST_ENTRIES:

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 5076

    # initContainers:
    #   update-volume-permissions:
    #     image: busybox:1.35.0
    #     command: ["/bin/sh", "-c"]
    #     args: ["chown -R 1000:1000 /config"]
    #     volumeMounts:
    #       - name: config
    #         mountPath: /config
    #     securityContext:
    #       runAsUser: 0

    # podSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    #   fsGroupChangePolicy: "OnRootMismatch"

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        hosts:
          - # -- Host address. Helm template can be passed.
            host: nzbhydra.lab.nickshores.net
            ## Configure the paths for the host
            paths:
              - # -- Path.  Helm template can be passed.
                path: /
                # -- Ignored if not kubeVersion >= 1.14-0
                pathType: Prefix
                service:
                  # -- Overrides the service name reference for this path
                  name:
                  # -- Overrides the service port reference for this path
                  port:

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        size: 20Gi
    probes:
      liveness:
        custom: true
        enabled: true
        spec:
          failureThreshold: 5
          httpGet:
            path: /actuator/health/ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
      readiness:
        custom: true
        enabled: true
        spec:
          failureThreshold: 5
          httpGet:
            path: /actuator/health/ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
      startup:
        custom: true
        enabled: true
        spec:
          failureThreshold: 5
          httpGet:
            path: /actuator/health/ping
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
