apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io/
      chart: longhorn
      version: 1.4.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: longhorn
  values:
    longhornManager:
      # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      nodeSelector:
        # Run longhorn components on-prem only
        location: "on-prem"
    longhornUI:
      # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      nodeSelector:
        # Run longhorn components on-prem only
        location: "on-prem"
    longhornDriver:
      # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      nodeSelector:
        # Run longhorn components on-prem only
        location: "on-prem"
    defaultSettings:
      # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
      systemManagedComponentsNodeSelector: "location:on-prem"
