apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.4.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: longhorn
