apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: home-assistant
  values:
    controller:
      # -- enable the controller.
      enabled: true
      # -- Set the controller type.
      # Valid options are deployment, daemonset or statefulset
      type: deployment
      # -- Set annotations on the deployment/statefulset/daemonset
      annotations:
        reloader.stakater.com/auto: "true"
      # -- Set labels on the deployment/statefulset/daemonset

    image:
      # -- image repository
      repository: ghcr.io/home-assistant/home-assistant
      # -- image tag
      # @default -- chart.appVersion
      tag: 2025.3.0
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: America/Los_Angeles
      # Temp fix for python issue https://github.com/home-assistant/core/issues/127966#issuecomment-2439414558
      PYTHONPATH: /usr/local/lib/python3.12:/config/deps
    # -- Configures service settings for the chart. Normally this does not need to be modified.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        hosts:
          - # -- Host address. Helm template can be passed.
            host: ha.nickshores.net
            ## Configure the paths for the host
            paths:
              - # -- Path.  Helm template can be passed.
                path: /
                # -- Ignored if not kubeVersion >= 1.14-0
                pathType: Prefix
                service:
                  # -- Overrides the service name reference for this path
                  name:
                  # -- Overrides the service port reference for this path
                  port:

    # -- Enable devices to be discoverable
    hostNetwork: true

    # -- When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
    # dnsPolicy: ClusterFirstWithHostNet

    securityContext:
      # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
      privileged: # true

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      #Create a general PVC that holds all persistent data that we don't track.
      config:
        enabled: true
        size: 20Gi
      #Mount a config map for each of our persistent configs we track in git.
      ha-configuration:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: home-assistant-configs
        subPath:
          - path: configuration.yaml
            mountPath: /config/configuration.yaml
      ha-automation:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: home-assistant-configs
        subPath:
          - path: automations.yaml
            mountPath: /config/automations.yaml
      ha-customize:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: home-assistant-configs
        subPath:
          - path: customize.yaml
            mountPath: /config/customize.yaml
      ha-secrets:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: ha-configmap-secret
        subPath:
          - path: secrets.yaml
            mountPath: /config/secrets.yaml

    # -- Enable and configure mariadb database subchart under this key.
    #    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
    # @default -- See values.yaml
    mariadb:
      enabled: false
      architecture: standalone
      auth:
        database: home-assistant
        username: home-assistant
        password: home-assistant-pass
        rootPassword: home-assistantrootpass
      primary:
        persistence:
          enabled: false
          # storageClass: ""

    # -- Enable and configure postgresql database subchart under this key.
    #    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
    # @default -- See values.yaml
    postgresql:
      enabled: false
      image:
        repository: bitnami/postgresql
        tag: 14.4.0
      postgresqlUsername: home-assistant
      postgresqlPassword: home-assistant-pass
      postgresqlDatabase: home-assistant
      persistence:
        primary:
          enabled: false
          # storageClass: ""

    # -- Enable and configure influxdb database subchart under this key.
    #    For more options see [influxdb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/influxdb)
    # @default -- See values.yaml
    influxdb:
      enabled: false
      architecture: standalone
      database: home_assistant
      authEnabled: false
      persistence:
        enabled: false
        # storageClass: ""
        # size: 8Gi

    metrics:
      # -- Enable and configure a Prometheus serviceMonitor for the chart under this key.
      # @default -- See values.yaml
      enabled: true
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 30s
        labels: {}
        ## See https://www.home-assistant.io/docs/authentication/ for where to find
        ## long lived access token creation under your account profile, which is
        ## needed to monitor Home Assistant
        # bearerTokenSecret:
        #   name: ""
        #   key: ""

      # -- Enable and configure Prometheus Rules for the chart under this key.
      # @default -- See values.yaml
      prometheusRule:
        enabled: true
        labels: {}
        # -- Configure additionial rules for the chart under this key.
        # @default -- See prometheusrules.yaml
        rules:
          - alert: HomeAssistantAbsent
            annotations:
              description: Home Assistant has disappeared from Prometheus service discovery.
              summary: Home Assistant is down.
            expr: |
              absent(up{job=~".*home-assistant.*"} == 1)
            for: 5m
            labels:
              severity: critical

    addons:
      # -- Enable and configure codeserver for the chart.
      #    This allows for easy access to configuration.yaml
      # @default -- See values.yaml
      codeserver:
        enabled: true
        args:
          - --auth
          - none
          - --user-data-dir
          - /data/config/.vscode
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /config/automations.yaml
            name: ha-automation
            subPath: automations.yaml
          - mountPath: /config/configuration.yaml
            name: ha-configuration
            subPath: configuration.yaml
          - mountPath: /config/customize.yaml
            name: ha-customize
            subPath: customize.yaml
