---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./helmrelease-home-assistant.yaml
configMapGenerator:
  - name: home-assistant-configs
    files:
      - automations.yaml
      - configuration.yaml
      - customize.yaml
generatorOptions:
  disableNameSuffixHash: true
