apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr
  namespace: home
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tdarr
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-home-lab-repo
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: tdarr
  values:
    #
    # IMPORTANT NOTE
    #
    # This chart inherits from our common library chart. You can check the default values/options here:
    # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
    #

    image:
      # -- image repository
      repository: ghcr.io/haveagitgat/tdarr
      # -- image tag
      # @default -- chart.appVersion
      tag: 2.27.02
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [image docs](https://hub.docker.com/r/haveagitgat/tdarr) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: UTC
      # -- tdarr web UI listening port (same as Service port)
      webUIPort: "{{ .Values.service.main.ports.http.port }}"
      # -- tdarr server binding address
      serverIP: 0.0.0.0
      # -- tdarr server listening port
      serverPort: "{{ .Values.service.main.ports.server.port }}"
      # -- Allow override for the pre-compiled tdarr ffmpeg binary
      ffmpegPath: ""
      # -- Set the container user id
      PUID: "1000"
      # -- Set the container group id
      PGID: "1000"
      internalNode: "true"

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8265
          server:
            enabled: true
            protocol: TCP
            port: 8266

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        hosts:
          - # -- Host address. Helm template can be passed.
            host: tdarr.nickshores.net
            ## Configure the paths for the host
            paths:
              - # -- Path.  Helm template can be passed.
                path: /
                # -- Ignored if not kubeVersion >= 1.14-0
                pathType: Prefix
                service:
                  # -- Overrides the service name reference for this path
                  name:
                  # -- Overrides the service port reference for this path
                  port:

    node:
      # -- Deploy a tdarr node.
      enabled: flase
      # -- Node ID
      id: node
      image:
        # -- image repository
        repository: haveagitgat/tdarr_node
        # -- image tag
        tag: 2.40.01
        # -- image pull policy
        pullPolicy: IfNotPresent
      # -- Node resources
      resources: {}

    # -- Configure persistence settings for the chart under this key.
    # @default -- See below
    persistence:
      # -- Volume used for configuration
      # @default -- See values.yaml
      config:
        enabled: true
        mountPath: /app/configs

      # -- Volume used for tdarr server database
      # @default -- See values.yaml
      data:
        enabled: true
        mountPath: /app/server
        accessMode: ReadWriteOnce
        storageClass: "longhorn"
        size: 5Gi

      # -- Volume used for media libraries
      # @default -- See values.yaml
      tv:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            path: /mnt/user/TV
            server: slimcloud.lab.nickshores.net
        mountPath: /tv

      # -- Volume used for shared storage. e.g. emptydir transcode
      # @default -- See values.yaml
      shared:
        enabled: true
        mountPath: /shared
