---
# tasks file for k3s-master

#prepare hosts for etcd

- name: set ionice tuning param for etcd
  shell: sudo ionice -c2 -n0 -p $(pgrep -f "k3s server")
  become: true

- name: install k3s on master[0]
  shell: >
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.25.13+k3s K3S_TOKEN={{ k3s_server_token }} INSTALL_K3S_EXEC="--disable traefik --disable servicelb --etcd-expose-metrics --cluster-init --etcd-arg heartbeat-interval=10000 --etcd-arg election-timeout=50000" sh -
  args:
    creates: /usr/local/bin/k3s
    warn: no
  register: master_install_result
  delegate_to: "{{ groups['k3s_masters'][0] }}"
  run_once: true

- set_fact:
    master_ip: "{{ hostvars[groups['k3s_masters'][0]].ansible_default_ipv4.address }}"

- name: install k3s on master[1-n]
  shell: >
    curl -sfL https://get.k3s.io |  K3S_TOKEN={{ k3s_server_token }} INSTALL_K3S_VERSION=v1.25.13+k3s1 INSTALL_K3S_EXEC="--disable traefik --disable servicelb --etcd-expose-metrics --server https://{{ master_ip }}:6443 --etcd-arg heartbeat-interval=10000 --etcd-arg election-timeout=50000" sh -
  args:
    creates: /usr/local/bin/k3s
    warn: no
  when: inventory_hostname != groups['k3s_masters'][0]

- name: setup kubectl auto-completion
  lineinfile:
    path: /root/.bash_profile
    regexp: 'source <\(kubectl completion bash\)'
    line: source <(kubectl completion bash)
    create: yes

- name: fetch k3s.yaml
  become: true
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig }}"
    flat: yes

- name: Label nodes based on group membership
  shell: >
    kubectl label node {{ inventory_hostname }}
    location={{ 'on-prem' if inventory_hostname in groups['on_prem'] else 'cloud' }}
  args:
    warn: no
  when: inventory_hostname in groups['k3s_masters'] or inventory_hostname in groups['k3s_workers']
  become: true
# - name: update master ip in k3s.yaml
#   become: true
#   replace:
#     path: "{{ kubeconfig }}"
#     regexp: "127.0.0.1"
#     replace: "{{ hostvars[groups['k3s_masters'][0]].ansible_default_ipv4.address }}"
#   delegate_to: localhost

# - name: update cluster name k3s.yaml
#   become: true
#   replace:
#     path: "{{ kubeconfig }}"
#     regexp: "default"
#     replace: "{{ cluster_name }}"
#   delegate_to: localhost
